name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble
      
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.2
        with:
          name: challenge-zup
          path: app/build/outputs/apk/debug/challeng-zup.apk
